SELECT *
FROM EMPLOYEE;

SELECT DEPARTMENT_NAME,MAX(SALARY) AS MAXIMUM
FROM EMPLOYEE
GROUP BY department_name;

SELECT E.*,
MAX(SALARY) OVER(PARTITION BY DEPARTMENT_NAME) AS MAX_SALARY
FROM EMPLOYEE E;