SELECT *
FROM EMPLOYEES;

--FIND TOP 3 SALARIES IN TABLE
SELECT *FROM(
SELECT EMPLOYEE_NAME,DEPARTMENT_NAME, SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEE
)WHERE DEN<4;

--FIND TOP 3 SALARIRIES DEPARTMENT WISE
SELECT *FROM(
SELECT EMPLOYEE_NAME,DEPARTMENT_NAME,SALARY,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT_NAME ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEE
)WHERE DEN<4
ORDER BY SALARY DESC;


CREATE TABLE EMPLOYEES
AS
SELECT *FROM 
HR.EMPLOYEES;



SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,SALARY,
ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROWNUMB,
RANK() OVER(ORDER BY SALARY DESC) AS RNK,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DEN,
LEAD(SALARY,2,0) OVER(ORDER BY SALARY DESC) AS LEAD_EMP,
LAG(SALARY) OVER(ORDER BY SALARY DESC) AS LAGG
FROM EMPLOYEES;


	  
SELECT *
FROM   employees outer
WHERE  EXISTS ( SELECT 'INDIA'
                 FROM   employees INNERR
                 WHERE  INNERR.manager_id =OUTER.MANAGER_ID);
                 
--101	Neena	Kochhar	NKOCHHAR	515.123.4568	21-09-05	AD_VP	17000		100	90
SELECT *
FROM   employees outer
WHERE  EXISTS ( SELECT 'INDIA'
                 FROM   employees INNERR
                 WHERE  INNERR.manager_id =OUTER.MANAGER_ID);
    
SELECT *FROM(
SELECT FIRST_NAME,LAST_NAME,SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEES                 
)WHERE DEN<4;





SELECT *FROM(
SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY TOTAL DESC
)WHERE ROWNUM<4;


SELECT *FROM(
SELECT FIRST_NAME,LAST_NAME,SALARY,
RANK() OVER(ORDER BY SALARY DESC) AS RNK
FROM EMPLOYEES
)WHERE RNK<4;


WITH TEMP1 AS(
SELECT DEPARTMENT_ID,SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK
FROM EMPLOYEES)

SELECT *FROM TEMP1
WHERE RNK<4;

--FETCH EMPLOYEES WHO EARNS MORE THAN AVG SALARY
----------------------------------------------------------






